config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'

  get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end
    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this Pin" if @pin.nil?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image )
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Photography", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to raw('<span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home'), root_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to raw('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Pin'), new_pin_path %></li>
          <li><%= link_to raw('<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Profile Settings'), edit_user_registration_path %></li>
          <li><%= link_to raw('<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Log out'), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to raw('<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Log in'), new_user_session_path %></li>
          <li><%= link_to raw('<span class="glyphicon glyphicon-user" aria-hidden="true"></span> Sign up'), new_user_registration_path %></li>
        <% end %>
        <li><%= link_to raw('<span class="glyphicon glyphicon-apple" aria-hidden="true"></span> About'), about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photograph</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to my App!</h1>
  <p>
    <%= link_to raw('<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Log in'), new_user_session_path, class: "btn btn-default" %>
    <%= link_to raw('<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Sign up'), new_user_registration_path, class: "btn btn-primary" %>
  </p>
</div>

app/views/pages/about.html.erb
<div class="row white">
  <h1>About Us</h1>
  <h2>The Team</h2>
  <h4>Deepak(CEO, technical lead, co-founder)</h4>
  <p>&copy; Copyright and All Rights Reserved to <i><b>Deepak</b></i></p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to my App!</h1>
  <% if user_signed_in? %>

  <% else %>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
  </p>
  <% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h1>Editing Pin</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Show', @pin %> |
    <%= link_to 'Back', pins_path %>
  </div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless signed_in?%>
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br>
        <strong><%= pin.user.name if pin.user %></strong>
        <% if current_user && (pin.user == current_user) %>
          <div class="actions">
            <%= link_to raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit'), edit_pin_path(pin) %> |
            <%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Destroy'), pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h1>New Pin</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', pins_path %>
  </div>
</div>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-info">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><strong><%= @pin.description %></p></strong>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>
        <% if current_user && (@pin.user == current_user) %>
          <%= link_to raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit'), edit_pin_path(@pin) %> |
          <%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Destroy'), @pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Back', pins_path %>
      </div>
    </div>
  </div>
</div>